CREATE TABLE situacao_aluno (
    ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE enderecos (
    ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    ALUNO_ID TEXT NOT NULL
);

CREATE TABLE alunos (
    ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    NOME_SOCIO VARCHAR(100),
    EMAIL_SOCIO VARCHAR(100),
    TELEFONE_SOCIO VARCHAR(11),
    DATA_ENTRADA TIMESTAMP,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VIGENCIA_CONTRATO INTEGER,
    DATA_RENOVACAO TIMESTAMP,
    DATA_ULTIMO_CONTRATO TIMESTAMP,
    ULTIMA_RESPOSTA INTEGER,
    STATUS_FINANCEIRO VARCHAR(100),
    NOTA VARCHAR(1),
    SATISFACAO VARCHAR(250),
    CICLO_MATRICULA INTEGER,
    RENOVADO INTEGER,
    RESPONSAVEL VARCHAR(100),
    ULTIMO_ACOMPANHAMENTO TIMESTAMP,
    PROXIMO_CONTATO TIMESTAMP,
    MENTORIA INTEGER,
    REMOVIDO INTEGER,
    SITUACAO_ID TEXT REFERENCES situacao_aluno(ID),
    ENDERECO_ID TEXT REFERENCES enderecos(ID)
);
