CREATE TABLE atendentes (
    ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL
);

CREATE TABLE pesquisa_nps (
    ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOTA INT NOT NULL,
    FEEDBACK VARCHAR(255) NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ALUNO_ID TEXT REFERENCES alunos(ID)
);

CREATE TABLE situacao_financeira (
    ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    COR VARCHAR(20) NOT NULL
);

CREATE TABLE enderecos (
    ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    ALUNO_ID TEXT NOT NULL
);

CREATE TABLE alunos (
    ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    NOME_SOCIO VARCHAR(100),
    EMAIL_SOCIO VARCHAR(100),
    TELEFONE_SOCIO VARCHAR(11),
    DATA_ENTRADA TIMESTAMP,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VIGENCIA_CONTRATO INTEGER,
    DATA_RENOVACAO TIMESTAMP,
    DATA_ULTIMO_CONTRATO TIMESTAMP,
    ULTIMA_RESPOSTA INTEGER,
    STATUS_FINANCEIRO VARCHAR(100),
    NOTA VARCHAR(1),
    SATISFACAO VARCHAR(250),
    CICLO_MATRICULA INTEGER,
    RENOVADO INTEGER DEFAULT 0,
    --RESPONSAVEL VARCHAR(100),
    ULTIMO_ACOMPANHAMENTO TIMESTAMP,
    PROXIMO_CONTATO TIMESTAMP,
    MENTORIA INTEGER DEFAULT 0,
    REMOVIDO INTEGER DEFAULT 0,
    SITUACAO_ID TEXT REFERENCES situacao_financeira(ID),
    ATENDENTE_ID TEXT REFERENCES atendentes(ID)
);
